### ISSUE TITLE
Assertion failure on Flutter 1.5

### ISSUE THREAD

**Issue by VasilyKrainov** [marcglasberg/network_to_file_image#1]
Using this string on Flutter 1.5.*
`Image(image: NetworkToFileImage(url: "http://example.com/someFile.png", file: myFile))`
gives assertion failure:
'package:flutter/src/painting/image_stream.dart': Failed assertion: line 121 pos 12: '_completer == null': is not true.
The same string works on Flutter 1.3.14 just fine

**Comment by jodymac** [comment]
This occurred on flutter 1.6 for me, backing down to v1.5.4-hotfix.2 fixed it for me.

**Comment by marcglasberg** [comment]
I'll update this plugin probably by the middle of June.

**Comment by marcglasberg** [comment]
If you want the plugin to work for Flutter version **1.5.4**, including the `informationCollector`, please use this specific plugin version:

    network_to_file_image: 2.0.0

If you want the plugin to work for Flutter version **1.7.8**, including the `informationCollector`, please use this specific plugin version:

    network_to_file_image: 1.7.8

Please note, the current plugin works for both Flutter versions **1.5.4** and **1.7.8**, but has no `informationCollector`:

    network_to_file_image: 2.0.1

The `informationCollector` is for debug only, and probably not important for most uses. In any case, I will release a new version with the `informationCollector` as soon as the next Flutter stable version above 1.7.8 is released.
