### ISSUE TITLE
Doesn't work for dev Channel, Flutter version 1.15.20.

### ISSUE THREAD

**Issue by 54lianxi** [marcglasberg/network_to_file_image#10]
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/network_to_file_image-2.2.8/lib/network_to_file_image.dart:750:8: Error: The method '_MockHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {}
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/network_to_file_image-2.2.8/lib/network_to_file_image.dart:732:8: Error: The method '_MockHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {}
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/network_to_file_image-2.2.8/lib/network_to_file_image.dart:750:8: Error: The method '_MockHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {}
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/network_to_file_image-2.2.8/lib/network_to_file_image.dart:732:8: Error: The method '_MockHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {}
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 840

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by 54lianxi** [comment]
that is my code:

`import 'dart:io';
import 'package:flutter/material.dart';
import 'package:network_to_file_image/network_to_file_image.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

Directory _appDocsDir;

void main() async {
  // You should get the Application Documents Directory only once.
  WidgetsFlutterBinding.ensureInitialized();
  _appDocsDir = await getApplicationDocumentsDirectory();

  runApp(MaterialApp(home: Demo()));
}

File fileFromDocsDir(String filename) {
  String pathName = p.join(_appDocsDir.path, filename);
  return File(pathName);
}

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text('Network to file image example')),
    body: Padding(
      padding: const EdgeInsets.all(30.0),
      child: Image(
          image: NetworkToFileImage(
            url: "https://upload.wikimedia.org/wikipedia/commons/1/17/Google-flutter-logo.png",
            file: fileFromDocsDir("flutter.png"),
            debug: true,
          )),
    ),
  );
}`

**Comment by marcglasberg** [comment]
@54lianxi What Flutter version are you using? Stable channel? Could you please provide me here with your `flutter doctor` output?

**Comment by 54lianxi** [comment]
E:\lianxiclub\flutter\emoji_store>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.15.20, on Microsoft Windows [Version 10.0.17763.1039], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.41.1)

**Comment by 54lianxi** [comment]
@marcglasberg

**Comment by marcglasberg** [comment]
@54lianxi You are in the **dev channel**, which the package can't yet support. Please, move to the **stable channel** and all will work. 

Thanks!

**Comment by 54lianxi** [comment]
you are right, thanks
