### ISSUE TITLE
Can I customize the path of cache pictures

### ISSUE THREAD

**Issue by 54lianxi** [marcglasberg/network_to_file_image#11]

**Comment by marcglasberg** [comment]
Sure. You should already create the file with the path you want, and pass it to the constructor as the `file` parameter:

```
NetworkToFileImage(
          url: "http://example.com/someFile.png", 
          file: myFile);
```

If you want that file to be in a specific directory, you must create that directory first. This is, however, just regular filesystem manipulation, and has nothing to do with the `NetworkToFileImage` class itself. I suggest you study how the `File` and `Directory` classes work in Dart.
