### ISSUE TITLE
I want to see the progress of the download,What shall I do?

### ISSUE THREAD

**Issue by 54lianxi** [marcglasberg/network_to_file_image#13]
I want to see the progress of the download,What shall I do?

**Comment by marcglasberg** [comment]
It's not possible with this widget. This is mean for small images that download in a second or so, and it's based upon https://api.flutter.dev/flutter/painting/NetworkImage-class.html which also doesn't have this functionality. 

If you want to show progress you can simply do something like:

    CircularProgressIndicator(valueColor: AlwaysStoppedAnimation<Color>(Colors.red));
