### ISSUE TITLE
Failure after Flutter 1.17 upgrade

### ISSUE THREAD

**Issue by jonny7737** [marcglasberg/network_to_file_image#15]
Compiler message:
../../dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/network_to_file_image-2.2.8/lib/network_to_file_image.dart:732:8: Error: The method '_MockHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {}
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^

**Comment by marcglasberg** [comment]
It should now work for version: 2.3.0
