### ISSUE TITLE
This plugin will not run on any of the new flutter versions

### ISSUE THREAD

**Issue by jodymac** [marcglasberg/network_to_file_image#2]
flutter version 1.6.7

file:///Users/jody/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/network_to
_file_image-1.0.4/lib/network_to_file_image.dart:110:31: Error: The argument
type 'Null Function(StringBuffer)' can't be assigned to the parameter type
'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'
 ('file:///Users/jody/Flutter/flutter/packages/flutter/lib/src/foundation/diagno
 stics.dart').
Try changing the type of the parameter, or casting the argument to
'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information)

**Comment by marcglasberg** [comment]
I'll update this plugin probably by the middle of June.

**Comment by marcglasberg** [comment]
If you want the plugin to work for Flutter version **1.5.4**, including the `informationCollector`, please use this specific plugin version:

    network_to_file_image: 2.0.0

If you want the plugin to work for Flutter version **1.7.8**, including the `informationCollector`, please use this specific plugin version:

    network_to_file_image: 1.7.8

Please note, the current plugin works for both Flutter versions **1.5.4** and **1.7.8**, but has no `informationCollector`:

    network_to_file_image: 2.0.1

The `informationCollector` is for debug only, and probably not important for most uses. In any case, I will release a new version with the `informationCollector` as soon as the next Flutter stable version above 1.7.8 is released.
