### ISSUE TITLE
NoSuchMethodError: The method '<optimized out>' was called on null.

### ISSUE THREAD

**Issue by f2acode** [marcglasberg/network_to_file_image#20]
I'm receiving the following error on Sentry report (that's why I couldn't reproduce the error or provide details of parameters used):

> NoSuchMethodError
> NoSuchMethodError: The method '<optimized out>' was called on null.
> Receiver: null
> Tried calling: <optimized out>()
> 
> Crashed in non-app: painting.dart in ImmutableBuffer.fromUint8List
> binding.dart in PaintingBinding.instantiateImageCodec at line 97
> network_to_file_image.dart in NetworkToFileImage._loadAsync at line 170
> network_to_file_image.dart in NetworkToFileImage.load at line 123
> image_provider.dart in ImageProvider.resolveStreamForKey.<fn> at line 504
> image_cache.dart in ImageCache.putIfAbsent at line 355
> image_provider.dart in ImageProvider.resolveStreamForKey at line 502
> image_provider.dart in ImageProvider.resolve.<fn> at line 333

One of the devices which is facing this issue:

> brand | "samsung"
> device | "on7xelte"
> display | "M1AJQ.G610MUBS7CTA1"
> hardware | "samsungexynos7870"
> id | "M1AJQ"
> isPhysicalDevice | true
> manufacturer | "samsung"
> model | "SM-G610M"
> product | "on7xelteub"
> supported32BitAbis | ["armeabi-v7a","armeabi"]
> supported64BitAbis | []
> supportedAbis | ["armeabi-v7a","armeabi"]

The code where I use the library:

```
Container(
    decoration: BoxDecoration(
        image: DecorationImage(
            image: NetworkToFileImage(
                url: image.remotePath,
                file: File(image.localPath),
            ),
            fit: BoxFit.cover,
        ),
        borderRadius: BorderRadius.all(
            Radius.circular(radius),
        ),
    ),
)
```

**Comment by marcglasberg** [comment]
Hey, there is really no useful information there for me. Sorry, but I need some real code with a reproducible problem, that I can easily run and see the problem by myself. Unless you can provide me that, I'll be unable to help.

**Comment by f2acode** [comment]
@marcglasberg Sure, I'm gonna try to log the values when this error occur, btw do you have some guess about which type of value would pass thought the package without errors and just crash in a inner function (`ImmutableBuffer.fromUint8List`)? This sounds very strange to me.

**Comment by marcglasberg** [comment]
Não tenho a menor ideia. Preciso de mais informação.
