### ISSUE TITLE
Integration with flutter_map not working

### ISSUE THREAD

**Issue by JaffaKetchup** [marcglasberg/network_to_file_image#22]
Hello,
Please see my issue on `flutter_map`'s repo about this issue. It includes code snippets and log outputs, as well as a more detailed report: [link to repo issue](https://github.com/fleaflet/flutter_map/issues/795).

The main gist of the issue is that the images are not taken from local storage when there is no internet.
If this sounds like something you could help with, I'd be very grateful.

Thanks.
Luka S

**Comment by JaffaKetchup** [comment]
Resolved. See linked repo issue above.

**Comment by marcglasberg** [comment]
I have added this information to the docs:


> ### Important:
> 
> The directory where you want to save the image must already exist in the local disk. 
> Otherwise, the image won't be saved.
>
