### ISSUE TITLE
Placeholder image or failure to load an image

### ISSUE THREAD

**Issue by Sam-Guru-In-Training** [marcglasberg/network_to_file_image#23]
Doubtless, I'm ignorant but I can't seem to detect when it's failed to download from the device AND from the web.  This is especially relevant the first time it seeks a photo from the web.

I'd like to provide a placeholder image, my users have Avatars which are a perfectly acceptable fallback.  But I can't fathom how to detect the failure situation.  It's not returning null!

It would be great to know how to detect failure, or even be able to have a placeholder fall back image which works for failure.

**Comment by kjawadDeveloper1** [comment]
Any update on it

**Comment by marcglasberg** [comment]
Showing the downloading/error placeholder is not the responsibility of the `ImageProvider`, but the `Image`.

https://api.flutter.dev/flutter/widgets/Image-class.html

You can use it like this:

```
Image(    
    image: NetworkToFileImage(...),
    loadingBuilder: ...
    errorBuilder: ...
);
```

In other words, simply provide the loadingBuilder to display something while the image is loading, and the errorBuilder to display something if the image fails to display.
