### ISSUE TITLE
Flutter 2.5 compatibility 

### ISSUE THREAD

**Issue by kjawadDeveloper1** [marcglasberg/network_to_file_image#28]
After upgrading from flutter 2.2  to 2.5 i am facing this error .

../../../.pub-cache/hosted/pub.dartlang.org/network_to_file_image-3.0.0/lib/network_to_file_image.dart:313:34: Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
      _realClient.authenticate = f;

**Comment by connlaoi** [comment]
I have the first occurrence as well as another one here:

```
.../network_to_file_image-3.0.0/lib/network_to_file_image.dart:318:39: Error: A value of type 'Future<bool> Function(String, int, String, String)?' 
can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' 
because 'String?' is nullable and 'String' isn't - 'Future' is from 'dart:async'.
      _realClient.authenticateProxy = f;
      ```

**Comment by imiaoyu** [comment]
I also encountered this problem. Do you have a solution

**Comment by Ali1Ammar** [comment]
i send a pull request to solve this #29 
for now you could use my clone 
```yaml
network_to_file_image: 
    git:
      url: https://github.com/Ali1Ammar/network_to_file_image.git
```

**Comment by JaffaKetchup** [comment]
I also have this issue
