### ISSUE TITLE
Storing downloaded images in folder

### ISSUE THREAD

**Issue by jodymac** [marcglasberg/network_to_file_image#3]
This package has worked great!  However, I would like to be able to store the downloaded images in an image directory rather than the root directory of the app with the word Documents prefixed and the package to look in that directory for the already downloaded image.

This will allow for cleaner storage and the ability to delete the contents of the folder to create a refresh on all the images.  I'm currently using it to download business logos that could change at any time to reflect seasons or years.  If they keep the same name of the image but replace it, I will always be serving the old image.

**Comment by khietlam** [comment]
You can setup your folder: 

```
Future<File> fileAvatar(String filename) async {
    Directory dir = await getApplicationDocumentsDirectory();
    Directory subDir = await new Directory('${dir.path}/Lam/Avatar/Images')
        .create(recursive: true);
    String pathName = p.join(subDir.path, filename);
    return File(pathName);
  }
```

**Comment by marcglasberg** [comment]
@jodymac Yes, as @khietlam said you can give it any File, in any directory that already exists. Does that answer your question, and can I close this issue?

**Comment by jodymac** [comment]
I haven't tried the code, but if you agree with the above working, then I'll give that a shot.  So go ahead and close, I'll give a shot as soon as I can.  Thanks to you both.
