### ISSUE TITLE
Another exception was thrown: Instance of 'DiagnosticsProperty'<void>

### ISSUE THREAD

**Issue by abilashgupta** [marcglasberg/network_to_file_image#30]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.22563.1], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.2)
[√] Connected device (4 available)

The package is not working in release mode. It shows grey box in app.
![dfc696a6-9558-47cd-b174-a29bff38946c](https://user-images.githubusercontent.com/65917321/156706392-f167e2f1-5ac8-44bd-870f-50abb5792d6b.jpg)
 
minSdkVersion 22
targetSdkVersion 30

**Comment by marcglasberg** [comment]
You are using a very old version of Flutter: 

```
[√] Flutter (Channel stable, 2.5.2 ...
```

The version I am using is:

```
Flutter (Channel stable, 2.10.3 ...
```

Please upgrade your version, by typing `flutter upgrade` in your terminal. Then, test again and let me know if that solved your problem.

**Comment by abilashgupta** [comment]
> You are using a very old version of Flutter:
> 
> ```
> [√] Flutter (Channel stable, 2.5.2 ...
> ```
> 
> The version I am using is:
> 
> ```
> Flutter (Channel stable, 2.10.3 ...
> ```
> 
> Please upgrade your version, by typing `flutter upgrade` in your terminal. Then, test again and let me know if that solved your problem.

My project is running without Null safety and I cannot upgrade to Null safety now, because it is hectic. Could u please suggest me a solution?

**Comment by marcglasberg** [comment]
Sure! The solution is for you to **fix an old version** of all packages you use, including network_to_file_image. Just test older versions until you find one that works.

```
some_package: 2.5.1 // This is version 2.5.1, fixed
some_package: ^2.5.1 // This is 2.5.1 <= version < 3.0.0
```

**Comment by abilashgupta** [comment]
Thank you for taking your precious time to address this issue and for the
reply.
Also thank you for creating this package. This is very helpful. 😇
