### ISSUE TITLE
LateInitializationError: Local 'bytes' has not been initialized

### ISSUE THREAD

**Issue by jeremiahseun** [marcglasberg/network_to_file_image#33]
I am always having this error. This is the full crashlytics console:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
LateInitializationError: Local 'bytes' has not been initialized.. Error thrown resolving an image codec.
-------------------------------------------------------------------
LateError._throwLocalNotInitialized (dart:_internal)
NetworkToFileImage._loadAsync (network_to_file_image.dart:169)
NetworkToFileImage.load (network_to_file_image.dart:120)
ImageProvider.resolveStreamForKey.<fn> (image_provider.dart:539)
ImageCache.putIfAbsent (image_cache.dart:382)
ImageProvider.resolveStreamForKey (image_provider.dart:526)
ImageProvider.resolve.<fn> (image_provider.dart:374)
ImageProvider._createErrorHandlerAndKey.<fn> (image_provider.dart:488)
SynchronousFuture.then (synchronous_future.dart:41)

```

**Comment by jeremiahseun** [comment]
My details below:
pubspec.yaml
```
environment:
  sdk: ">=2.18.0"  # Dart version
  flutter: ^3.10.0

network_to_file_image: ^4.0.1
```

**Comment by demirdemirel** [comment]
I am having trouble with the same error.
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following LateError was thrown resolving an image codec:
LateInitializationError: Local 'bytes' has not been initialized.

When the exception was thrown, this was the stack:
#0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:197:5)
internal_patch.dart:197
#1      NetworkToFileImage._loadAsync (package:network_to_file_image/src/network_to_file_image.dart:169:21)
network_to_file_image.dart:169
#2      NetworkToFileImage.load (package:network_to_file_image/src/network_to_file_image.dart:120:16)
```

I think it was happened after I switched to null safety.
`environment:
  sdk: ">=2.12.0 <3.0.0"
  network_to_file_image: ^4.0.0
  `

**Comment by marcglasberg** [comment]
Could you please test it with the newest package version. 

And in case you still see the problem, could you please provide some code to demonstrate it? Please provide some very minimum code, that I can paste in a standalone file with main method and all, that I can run myself easily. Thank you!

**Comment by marcglasberg** [comment]
Could you please test it with the newest package version: [5.0.3] ?

It should probably solve the error. However, please note that the reason 'bytes' would not have been initialized is when you try to open a file that doesn't exist and then you don't provide the URL. Of course, it should not throw an error in this situation, but simply not download anything, which is what it's doing now.

And in case you still see the problem, could you please provide some code to demonstrate it? Please provide some very minimum code, that I can paste in a standalone file with main method and all, that I can run myself easily. Thank you!

**Comment by marcglasberg** [comment]
Could you please test it with the newest package version: [6.0.0] ?

It should probably solve the error. However, please note that the reason 'bytes' would not have been initialized is when you try to open a file that doesn't exist and then you don't provide the URL. Of course, it should not throw an error in this situation, but simply not download anything, which is what it's doing now.
