### ISSUE TITLE
The loadingProgress parameter (of the loadingBuilder) is always null

### ISSUE THREAD

**Issue by Dicksenz** [marcglasberg/network_to_file_image#34]
when using loadingBuilder, the loadingProgress is always null

**Comment by marcglasberg** [comment]
Could you please provide some code to demonstrate the problem? Please provide some very minimum code, that I can paste in a standalone file with main method and all, that I can run myself easily. Thank you!

**Comment by marcglasberg** [comment]
Closing this as no code was provided.
