### ISSUE TITLE
image file storage persistent ?

### ISSUE THREAD

**Issue by jonny7737** [marcglasberg/network_to_file_image#5]
Are images stored locally with this package persisted across reboots / restarts of the phone and app?  I ask because debug logs seem to indicate that after every reboot / restart, all images are fetched from the network and subsequently read from file.  The image files are there.  Why are they read from the network OR am I just reading the logs incorrectly?

Fetching image from: https://rxpillimage.nlm.nih.gov/RxImage/image/images/gallery/600/29300-0243-10_RXNAVIMAGE10_8A3DC52E.jpg
Fetching image from: https://rxpillimage.nlm.nih.gov/RxImage/image/images/gallery/600/16729-0006-17_RXNAVIMAGE10_5812AC25.jpg
Reading image file: /data/user/0/domainhere/app_flutter/images/308135.jpg
Reading image file: /data/user/0/domainhere/app_flutter/images/198211.jpg

**Comment by marcglasberg** [comment]
It will **save** the image file. So it's persisted, yes, unless the file is deleted. If you put it in a temp directory the system may delete the file, and then it will fetch again. Or if you are using a simulator it may not persist across reboots. 

Unless there is some bug, of course. The save code is this, which seems correct:

```
  void saveImageToTheLocalFile(Uint8List bytes) async {
    if (debug) print("Saving image to file: ${file?.path}");
    file.writeAsBytes(bytes, flush: true);
  }
```

Could you please provide me with some small, standalone, runnable code which I can use to see the problem you describe?

**Comment by jonny7737** [comment]
I will put together a small example.

The save code does seem correct but I do not see logs indicating "Saving image to file".

**Comment by jonny7737** [comment]
While writing the sample code, I found my problem.  My file path is not being setup soon enough and so it is null;

Apologies for the false alarm and thank you for the help.

**Comment by marcglasberg** [comment]
@jonny7737 You're welcome.
