### ISSUE TITLE
Default image

### ISSUE THREAD

**Issue by ghost** [marcglasberg/network_to_file_image#7]
What if the connection failed and image is not downloaded yet  it's better to use 
a default image instead of throwing exception every time.

**Comment by marcglasberg** [comment]
Showing the downloading/error placeholder is not the responsibility of the ImageProvider. 

I suggest using the FadeInImage:

   https://api.flutter.dev/flutter/widgets/FadeInImage-class.html

You can use it like this:

    FadeInImage(    
        placeholder: defaultImage,
        image: NetworkToFileImage(...),
    );
