### ISSUE TITLE
Clarify differences to cached_network_image

### ISSUE THREAD

**Issue by nioncode** [marcglasberg/network_to_file_image#8]
Could you please provide a few sentences in the description of the package about how it differs from https://pub.dev/packages/cached_network_image, i.e. what are the pros and cons of both / when to use one vs the other?

**Comment by marcglasberg** [comment]
Cached_network_image will cache an image for some time, and then evict the image from the cache when the cache gets full, or according to other conditions.

Meanwhile, network_to_file_image will simply download the image and leave it there. Think WhatsApp: someone sends you an image, it is downloaded and it's kept there, in your Gallery/files until someone deletes it manually. Also, network_to_file_image is much lighter than cached_network_image, which uses SQLite under the hood.
